---
- name: Create Ansible user account with 2048 bit SSH key
  hosts: all

  tasks:
  - name: Create Ansible user account with 2048 bit SSH key
    user:
      name: ansible
      shell: /bin/bash
      comment: Ansible SSH account
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      ssh_key_passphrase: test123