---
- name: Deploy Hashicorp Vault
  hosts: all

  tasks:
  - name: Download Hashicorp Vault with SHA verification
    get_url: 
      url: https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_linux_amd64.zip
      dest: /tmp/
      checksum: sha256:f2bca89cbffb8710265eb03bc9452cc316b03338c411ba8453ffe7419390b8f1

  - name: Install Unzip package
    apt:
      name: unzip
      state: latest
      update_cache: yes

  - name: Unzip Hashicorp Vault
    unarchive:
      src: /tmp/vault_1.4.2_linux_amd64.zip
      dest: /usr/local/bin/
      remote_src: yes

  - name: Enable Hashicorp Vault auto-complete install
    command: vault -autocomplete-install

  - name: Gather facts for .bashrc
    shell: cat /root/.bashrc
    register: bashsrc_output

  - name: Enable Hashicorp Vault command auto-completion in .bashrc if it doesn't already exist
    when: bashsrc_output.stdout.find('complete -C /usr/local/bin/vault vault') != -1
    lineinfile:
      path: /root/.bashrc
      line: complete -C /usr/local/bin/vault vault
      create: yes

  - name: Create vault directory in /etc/ for Hashicorp Vault
    file:
      path: /etc/vault
      state: directory
      mode: '0755'

  - name: Recursively create vault directories in /var/lib/ for Hashicorp Vault
    file:
      path: /var/lib/vault/data
      state: directory
      mode: '0755'